# =============================================================================
# AI RESEARCH ASSISTANT - AGENT CONFIGURATION
# =============================================================================
# This file defines the behavior and capabilities of each AI agent

# =============================================================================
# GLOBAL AGENT SETTINGS
# =============================================================================
global:
  # Default LLM settings
  default_model: "llama-3.1-70b-versatile"
  fast_model: "llama-3.1-8b-instant"
  reasoning_model: "llama-3.1-70b-versatile"
  
  # Temperature settings for different tasks
  creative_temperature: 0.7
  analytical_temperature: 0.3
  factual_temperature: 0.1
  
  # Token limits
  max_tokens: 4000
  max_context_length: 128000
  
  # Timeout settings (seconds)
  default_timeout: 300
  quick_timeout: 60
  deep_timeout: 600
  
  # Memory settings
  memory_window: 10  # Number of previous interactions to remember
  long_term_memory: true

# =============================================================================
# RESEARCHER AGENT CONFIGURATION
# =============================================================================
researcher:
  # Agent Identity
  role: "Senior Research Specialist"
  backstory: |
    You are a meticulous Senior Research Specialist with over 10 years of experience 
    in academic and industry research. You have a PhD in Information Science and 
    expertise in data gathering, source verification, and comprehensive analysis. 
    You're known for your ability to find relevant, credible sources and extract 
    key insights quickly.
  
  # Goals and Objectives
  goal: |
    Conduct thorough research on given topics, gather comprehensive information 
    from multiple reliable sources, and provide well-structured, factual data 
    that serves as a solid foundation for analysis and writing.
  
  # LLM Configuration
  llm:
    model: "llama-3.1-70b-versatile"
    temperature: 0.3
    max_tokens: 4000
    
  # Capabilities and Tools
  tools:
    - web_search
    - document_analysis
    - fact_verification
    - source_credibility_check
    - data_extraction
    
  # Behavior Settings
  behavior:
    max_search_results: 15
    min_sources_required: 3
    credibility_threshold: 0.7
    fact_check_enabled: true
    citation_format: "APA"
    
  # Performance Limits
  limits:
    timeout_seconds: 300
    max_iterations: 5
    max_output_length: 8000
    
  # Quality Metrics
  quality_checks:
    source_diversity: true
    recency_preference: true  # Prefer recent sources
    authority_verification: true
    bias_detection: true
    
  # Output Format
  output_format:
    include_sources: true
    include_confidence_scores: true
    structured_summary: true
    key_findings: true

# =============================================================================
# ANALYST AGENT CONFIGURATION
# =============================================================================
analyst:
  # Agent Identity
  role: "Strategic Data Analyst"
  backstory: |
    You are a Strategic Data Analyst with extensive experience in business 
    intelligence, market research, and strategic planning. You hold an MBA 
    and have worked with Fortune 500 companies. You excel at identifying 
    patterns, drawing insights from complex data, and providing strategic 
    recommendations based on thorough analysis.
  
  # Goals and Objectives
  goal: |
    Analyze research data comprehensively, identify key patterns and trends, 
    synthesize information from multiple sources, and provide strategic insights 
    and actionable recommendations based on the findings.
  
  # LLM Configuration
  llm:
    model: "llama-3.1-70b-versatile"
    temperature: 0.4
    max_tokens: 4000
    
  # Capabilities and Tools
  tools:
    - data_analysis
    - pattern_recognition
    - trend_analysis
    - statistical_analysis
    - comparative_analysis
    - swot_analysis
    - risk_assessment
    
  # Behavior Settings
  behavior:
    analysis_depth: "comprehensive"
    include_visualizations: true
    comparative_analysis: true
    trend_identification: true
    risk_assessment: true
    
  # Performance Limits
  limits:
    timeout_seconds: 180
    max_iterations: 4
    max_output_length: 6000
    
  # Analysis Framework
  frameworks:
    primary: "SWOT"
    secondary: ["PEST", "5_Forces", "Value_Chain"]
    custom_metrics: true
    
  # Quality Metrics
  quality_checks:
    logical_consistency: true
    evidence_based_conclusions: true
    balanced_perspective: true
    actionable_insights: true
    
  # Output Format
  output_format:
    executive_summary: true
    key_insights: true
    recommendations: true
    risk_factors: true
    confidence_intervals: true

# =============================================================================
# WRITER AGENT CONFIGURATION
# =============================================================================
writer:
  # Agent Identity
  role: "Professional Content Writer"
  backstory: |
    You are a Professional Content Writer with 8+ years of experience in 
    creating compelling, well-structured content for various audiences. 
    You have expertise in technical writing, marketing copy, and academic 
    publications. You're skilled at translating complex information into 
    clear, engaging, and actionable content.
  
  # Goals and Objectives
  goal: |
    Create well-structured, engaging, and professional content based on 
    research findings and analysis. Ensure the content is tailored to the 
    target audience, maintains high quality standards, and effectively 
    communicates key insights and recommendations.
  
  # LLM Configuration
  llm:
    model: "llama-3.1-70b-versatile"
    temperature: 0.6
    max_tokens: 4000
    
  # Capabilities and Tools
  tools:
    - content_structuring
    - tone_adaptation
    - style_optimization
    - readability_enhancement
    - citation_formatting
    - grammar_checking
    
  # Writing Styles
  styles:
    default: "professional"
    available: ["academic", "business", "technical", "casual", "persuasive"]
    tone_options: ["formal", "conversational", "authoritative", "friendly"]
    
  # Behavior Settings
  behavior:
    audience_adaptation: true
    seo_optimization: false
    readability_focus: true
    citation_inclusion: true
    structure_templates: true
    
  # Performance Limits
  limits:
    timeout_seconds: 240
    max_iterations: 3
    max_output_length: 10000
    min_output_length: 500
    
  # Content Quality
  quality_standards:
    grammar_check: true
    plagiarism_check: true
    readability_score: "college_level"
    coherence_check: true
    
  # Output Formats
  formats:
    default: "markdown"
    available: ["markdown", "html", "pdf", "docx"]
    templates: ["report", "article", "summary", "proposal"]
    
  # Structure Templates
  templates:
    report:
      sections: ["executive_summary", "introduction", "findings", "analysis", "recommendations", "conclusion"]
      min_words_per_section: 100
    article:
      sections: ["introduction", "main_content", "conclusion", "references"]
      style: "engaging"
    summary:
      sections: ["overview", "key_points", "implications"]
      style: "concise"

# =============================================================================
# WORKFLOW CONFIGURATION
# =============================================================================
workflow:
  # Task Execution Order
  execution_order:
    - researcher
    - analyst  
    - writer
    
  # Collaboration Settings
  collaboration:
    inter_agent_communication: true
    shared_memory: true
    feedback_loops: true
    quality_gates: true
    
  # Quality Gates
  quality_gates:
    researcher_gate:
      min_sources: 3
      credibility_threshold: 0.7
      completeness_check: true
    analyst_gate:
      insights_threshold: 5
      logical_consistency: true
      evidence_backing: true
    writer_gate:
      readability_score: 60
      structure_completeness: true
      citation_accuracy: true
      
  # Error Handling
  error_handling:
    max_retries: 3
    fallback_strategies: true
    graceful_degradation: true
    error_reporting: true
    
  # Performance Monitoring
  monitoring:
    execution_time_tracking: true
    quality_metrics: true
    user_satisfaction: true
    resource_usage: true

# =============================================================================
# INTEGRATION SETTINGS
# =============================================================================
integrations:
  # External APIs
  search_apis:
    primary: "serpapi"  # Configure in .env
    fallback: "bing"
    
  # Document Processing
  document_processing:
    enabled: true
    supported_formats: ["pdf", "docx", "txt", "md", "html"]
    max_file_size: "10MB"
    
  # Database Integration
  database:
    cache_results: true
    cache_duration: "24h"
    backup_enabled: true